name: fluxpart-env
channels:
  - defaults
  - ussl
  - conda-forge
dependencies:
  - python=3.5
  - fluxpart=0.1.0
  - ipython=5.1.*
  - jupyter=1.0.*
  - matplotlib=1.5.*
  - numpy=1.11.*
  - pytest=2.9.*
  - pywavelets=0.4.0
  - scipy=0.18.*
