{% set version = "0.1.0.dev0" %}

package:
  name: fluxpart
  version: {{ version }}

source:
  fn: fluxpart-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/b7/f0/f60ec38a12ec043c9cfe9d33dcaf0a47728e12060ba40d8d6242cb99fd07/fluxpart-{{ version }}.tar.gz
  md5: e7b25b8b8fd7c2f137c7ada927d87f34

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pywavelets

  run:
    - python
    - numpy
    - scipy
    - pywavelets

test:
  imports:
    - fluxpart
  requires:
    - pytest

about:
  home: https://github.com/usda-ars-ussl/fluxpart
  license: Public Domain CC0
  summary: 'Partition water vapor and carbon dioxide fluxes'
  license_family: Public-Domain
